### ISSUE TITLE
[Bug]: Laravel 10 + Livewire 3 Compatiblitiy

### ISSUE THREAD

**Issue by mmoollllee** [yannkuesthardt/Laravel-SpamProtect#1]
### What happened?

With every `wire:navigate` there is this error in the console:
`Uncaught SyntaxError: redeclaration of let encryptionKey`

### How to reproduce the bug

Setup with current Laravel & Livewire to make a route change using `wire:navigate`

### Package Version

1.2

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

macOS

### Notes

Livewire 3 says we shouldn't rely on `DOMContentLoaded`, see [Livewire Documentation](https://livewire.laravel.com/docs/navigate#dont-rely-on-domcontentloaded)

**Comment by yannkuesthardt** [comment]
@mmoollllee Thank you for reporting that bug. I've added support for Livewire v3 navigation in v1.2.1.

You might have to republish the vendor app.js for the fix to work.
